### ISSUE TITLE
Not tracking added files under any_changed

### ISSUE THREAD

**Issue by danielstaleiny** [tj-actions/changed-files#1429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I believe that the newly created files should be tracked as any_changed -> true.

I can see from debugger that the file is among the other_chaged_files instead. 
##[debug]Set output other_changed_files = supabase/migrations/test.sql
##[debug]Set output other_changed_files_count = 1

### To Reproduce

      - name: check for migration changes
        id: db-changed
        uses: tj-actions/changed-files@v37
        with:
          files: |
            supabase/migrations/**/*
            supabase/config.toml

add file in the path. 
the any_changed flag is still false. 

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

     this should be steps.db-changed.outputs.any_changed == 'true'

### Relevant log output

```shell
0s
##[debug]Evaluating condition for step: 'check for migration changes'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: check for migration changes
##[debug]Loading inputs
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: github.api_url
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'api_url'
##[debug]=> 'https://api.github.com'
##[debug]Result: 'https://api.github.com'
##[debug]Loading env
Run tj-actions/changed-files@v37
::group::changed-files
changed-files
::group::changed-files-patterns
changed-files-patterns
  ##[debug]All filtered diff files: {"A":[],"C":[],"D":[],"M":[],"R":[],"T":[],"U":[],"X":[]}
  ##[debug]Added files: {"paths":"","count":"0"}
  ##[debug]Copied files: {"paths":"","count":"0"}
  ##[debug]Modified files: {"paths":"","count":"0"}
  ##[debug]Renamed files: {"paths":"","count":"0"}
  ##[debug]Type changed files: {"paths":"","count":"0"}
  ##[debug]Unmerged files: {"paths":"","count":"0"}
  ##[debug]Unknown files: {"paths":"","count":"0"}
  ##[debug]All changed and modified files: {"paths":"","count":"0"}
  ##[debug]All changed files: {"paths":"","count":"0"}
  ##[debug]All other changed files: {"paths":"supabase/migrations/test.sql","count":"1"}
  ##[debug]All modified files: {"paths":"","count":"0"}
  ##[debug]Deleted files: {"paths":"","count":"0"}
  All Done!
  ::endgroup::
##[debug]Node Action run completed with exit code 0
##[debug]Set output added_files = 
##[debug]Set output added_files_count = 0
##[debug]Set output copied_files = 
##[debug]Set output copied_files_count = 0
##[debug]Set output modified_files = 
##[debug]Set output modified_files_count = 0
##[debug]Set output renamed_files = 
##[debug]Set output renamed_files_count = 0
##[debug]Set output type_changed_files = 
##[debug]Set output type_changed_files_count = 0
##[debug]Set output unmerged_files = 
##[debug]Set output unmerged_files_count = 0
##[debug]Set output unknown_files = 
##[debug]Set output unknown_files_count = 0
##[debug]Set output all_changed_and_modified_files = 
##[debug]Set output all_changed_and_modified_files_count = 0
##[debug]Set output all_changed_files = 
##[debug]Set output all_changed_files_count = 0
##[debug]Set output any_changed = false
##[debug]Set output only_changed = false
##[debug]Set output other_changed_files = supabase/migrations/test.sql
##[debug]Set output other_changed_files_count = 1
##[debug]Set output all_modified_files = 
##[debug]Set output all_modified_files_count = 0
##[debug]Set output any_modified = false
##[debug]Set output only_modified = false
##[debug]Set output other_modified_files = supabase/migrations/test.sql
##[debug]Set output other_modified_files_count = 1
##[debug]Set output deleted_files = 
##[debug]Set output deleted_files_count = 0
##[debug]Set output any_deleted = false
##[debug]Set output only_deleted = false
##[debug]Set output other_deleted_files = 
##[debug]Set output other_deleted_files_count = 0
##[debug]Finishing: check for migration changes
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@danielstaleiny I believe this is an issue with the pattern you specified.

I’ll suggest changing `supabase/migrations/**/*` to `supabase/migrations/**`

**Comment by danielstaleiny** [comment]
Can you give me hint what glob pattern should I make to capture both, new files in folder and changes in subfolders ? 

If I change the glob to your suggestion, I no longer see any_changed = true if I change something in file under subfolder. 

```
      - name: check for file changes
        id: v2-generate-next-season
        uses: tj-actions/changed-files@v37
        with:
          files: |
            supabase/functions/v2-generate-next-season/**.{js,ts,json}
            supabase/functions/_src/**.{js,ts,json}
      - name: check for global file changes
        id: v2-generate-next-season-global
        uses: tj-actions/changed-files@v37
        with:
          files: |
            supabase/functions/_src/**.{js,ts,json}

```
File changed,  supabase/functions/_src/season-data/s01.ts

```
##[debug]Evaluating condition for step: 'check for file changes'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: check for file changes
##[debug]Loading inputs
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: github.api_url
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'api_url'
##[debug]=> 'https://api.github.com/'
##[debug]Result: 'https://api.github.com/'
##[debug]Loading env
Run tj-actions/changed-files@v37
::group::changed-files
changed-files
::group::changed-files-patterns
changed-files-patterns
##[debug]Node Action run completed with exit code 0
##[debug]Set output added_files = 
##[debug]Set output added_files_count = 0
##[debug]Set output copied_files = 
##[debug]Set output copied_files_count = 0
##[debug]Set output modified_files = 
##[debug]Set output modified_files_count = 0
##[debug]Set output renamed_files = 
##[debug]Set output renamed_files_count = 0
##[debug]Set output type_changed_files = 
##[debug]Set output type_changed_files_count = 0
##[debug]Set output unmerged_files = 
##[debug]Set output unmerged_files_count = 0
##[debug]Set output unknown_files = 
##[debug]Set output unknown_files_count = 0
##[debug]Set output all_changed_and_modified_files = 
##[debug]Set output all_changed_and_modified_files_count = 0
##[debug]Set output all_changed_files = 
##[debug]Set output all_changed_files_count = 0
##[debug]Set output any_changed = false
##[debug]Set output only_changed = false
##[debug]Set output other_changed_files = .github/workflows/deploy.yml supabase/functions/_src/season-data/s01.ts
##[debug]Set output other_changed_files_count = 2
##[debug]Set output all_modified_files = 
##[debug]Set output all_modified_files_count = 0
##[debug]Set output any_modified = false
##[debug]Set output only_modified = false
##[debug]Set output other_modified_files = .github/workflows/deploy.yml supabase/functions/_src/season-data/s01.ts
##[debug]Set output other_modified_files_count = 2
##[debug]Set output deleted_files = 
##[debug]Set output deleted_files_count = 0
##[debug]Set output any_deleted = false
##[debug]Set output only_deleted = false
##[debug]Set output other_deleted_files = 
##[debug]Set output other_deleted_files_count = 0
##[debug]Finishing: check for file changes
```

**Comment by jackton1** [comment]
Interesting, I'll reopen this issue so I can investigate

**Comment by jackton1** [comment]
@danielstaleiny In the meantime can include the configuration you have for the checkout action ?

**Comment by danielstaleiny** [comment]
Here is file for example. 
```
name: main/dev deployment workflow
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'supabase/**'

jobs:
  db-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setting environment variables
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "MAIN ENV"
            echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV
            echo "SUPABASE_JWT=${{ secrets.MAIN_SUPABASE_JWT }}" >> $GITHUB_ENV
            echo "PROJECT_ID=${{ secrets.MAIN_PROJECT_ID }}" >> $GITHUB_ENV
            echo "PROJECT_ID=${{ secrets.MAIN_PROJECT_ID }}" >> $GITHUB_ENV
            echo "DB_PW=${{ secrets.MAIN_DB_PW }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "DEV ENV"
            echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV
            echo "SUPABASE_JWT=${{ secrets.DEV_SUPABASE_JWT }}" >> $GITHUB_ENV
            echo "PROJECT_ID=${{ secrets.DEV_PROJECT_ID }}" >> $GITHUB_ENV
            echo "DB_PW=${{ secrets.DEV_DB_PW }}" >> $GITHUB_ENV
          fi
      - name: check for migration changes
        id: db-changed
        uses: tj-actions/changed-files@v37
        with:
          files: |
            supabase/migrations/**
            supabase/config.toml
      - uses: supabase/setup-cli@v1
        if: steps.db-changed.outputs.any_changed == 'true'
        with:
          version: latest
      - name: Sup version
        if: steps.db-changed.outputs.any_changed == 'true'
        run: supabase --version
      - name: Run link project if db changes
        if: steps.db-changed.outputs.any_changed == 'true'
        run: supabase link --password "$DB_PW" --project-ref "$PROJECT_ID"
      - name: Run migration if db changes
        if: steps.db-changed.outputs.any_changed == 'true'
        run: supabase db push --password "$DB_PW"

  fn-ai-queue:
    runs-on: ubuntu-latest
    needs: db-migration
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setting environment variables
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "MAIN ENV"
            echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV
            echo "SUPABASE_JWT=${{ secrets.MAIN_SUPABASE_JWT }}" >> $GITHUB_ENV
            echo "PROJECT_ID=${{ secrets.MAIN_PROJECT_ID }}" >> $GITHUB_ENV
            echo "DB_PW=${{ secrets.MAIN_DB_PW }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "DEV ENV"
            echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV
            echo "SUPABASE_JWT=${{ secrets.DEV_SUPABASE_JWT }}" >> $GITHUB_ENV
            echo "PROJECT_ID=${{ secrets.DEV_PROJECT_ID }}" >> $GITHUB_ENV
            echo "DB_PW=${{ secrets.DEV_DB_PW }}" >> $GITHUB_ENV
          fi
      - name: check for file changes
        id: ai-queue
        uses: tj-actions/changed-files@v37
        with:
          files: |
            supabase/functions/ai_queue/**.{js,ts,json}
            supabase/functions/_src/**.{js,ts,json}
      - uses: supabase/setup-cli@v1
        if: steps.ai-queue.outputs.any_changed == 'true'
        with:
          version: latest
      - name: Sup version
        if: steps.ai-queue.outputs.any_changed == 'true'
        run: supabase --version
      - name: Run deploy functions
        if: steps.ai-queue.outputs.any_changed == 'true'
        run: supabase functions deploy ai_queue --project-ref "$PROJECT_ID"

      - name: Run health check
        if: steps.ai-queue.outputs.any_changed == 'true'
        run: |
          sleep 2s && curl -f -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" \
          -H "x-health-check: true" \
          -H "Authorization: Bearer $SUPABASE_JWT" \
          https://$PROJECT_ID.functions.supabase.co/functions/v1/ai_queue
  
```


![image](https://github.com/tj-actions/changed-files/assets/12045962/70e1bf41-1ea5-4de7-9be7-6449402fa045)
Proof that it skips over. 

and Here are the logs. 
```
1s
##[debug]Evaluating condition for step: 'check for file changes'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: check for file changes
##[debug]Loading inputs
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: github.api_url
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'api_url'
##[debug]=> 'https://api.github.com/'
##[debug]Result: 'https://api.github.com/'
##[debug]Loading env
Run tj-actions/changed-files@v37
::group::changed-files
changed-files
::group::changed-files-patterns
changed-files-patterns
##[debug]Node Action run completed with exit code 0
##[debug]Set output added_files = 
##[debug]Set output added_files_count = 0
##[debug]Set output copied_files = 
##[debug]Set output copied_files_count = 0
##[debug]Set output modified_files = 
##[debug]Set output modified_files_count = 0
##[debug]Set output renamed_files = 
##[debug]Set output renamed_files_count = 0
##[debug]Set output type_changed_files = 
##[debug]Set output type_changed_files_count = 0
##[debug]Set output unmerged_files = 
##[debug]Set output unmerged_files_count = 0
##[debug]Set output unknown_files = 
##[debug]Set output unknown_files_count = 0
##[debug]Set output all_changed_and_modified_files = 
##[debug]Set output all_changed_and_modified_files_count = 0
##[debug]Set output all_changed_files = 
##[debug]Set output all_changed_files_count = 0
##[debug]Set output any_changed = false
##[debug]Set output only_changed = false
##[debug]Set output other_changed_files = .github/workflows/deploy.yml supabase/functions/_src/season-data/s01.ts
##[debug]Set output other_changed_files_count = 2
##[debug]Set output all_modified_files = 
##[debug]Set output all_modified_files_count = 0
##[debug]Set output any_modified = false
##[debug]Set output only_modified = false
##[debug]Set output other_modified_files = .github/workflows/deploy.yml supabase/functions/_src/season-data/s01.ts
##[debug]Set output other_modified_files_count = 2
##[debug]Set output deleted_files = 
##[debug]Set output deleted_files_count = 0
##[debug]Set output any_deleted = false
##[debug]Set output only_deleted = false
##[debug]Set output other_deleted_files = 
##[debug]Set output other_deleted_files_count = 0
##[debug]Finishing: check for file changes
```

**Comment by danielstaleiny** [comment]
thank you for looking into this. I guess I would fix it by running combination of 
**/*.{js,ts,json}
**.{js,ts,json}

which both looked okeyish. Yesterday I had **.{} what you have suggested, but then I had issues with catching the file changes under subdirectory, therefore I changed it to **/*.{} and end-up with issue with new files. Which resulted in confusion.

**Comment by danielstaleiny** [comment]
Simplified version still running to the same issue. changes are not picked up by
            supabase/functions/ai_queue/**.{js,ts,json}
            supabase/functions/_src/**.{js,ts,json}


in the file 
  supabase/functions/_src/season-data/s01.ts
  
  ```
  name: test build
on:
  push:
    branches:
      - develop
jobs:
  fn-ai-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: check for file changes
        id: ai-queue
        uses: tj-actions/changed-files@v37
        with:
          files: |
            supabase/functions/ai_queue/**.{js,ts,json}
            supabase/functions/_src/**.{js,ts,json}
      - uses: supabase/setup-cli@v1
        if: steps.ai-queue.outputs.any_changed == 'true'
        with:
          version: latest
      - name: Sup version
        if: steps.ai-queue.outputs.any_changed == 'true'
        run: supabase --version
``` 

logs
```
##[debug]Evaluating condition for step: 'check for file changes'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: check for file changes
##[debug]Loading inputs
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: github.api_url
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'api_url'
##[debug]=> 'https://api.github.com/'
##[debug]Result: 'https://api.github.com/'
##[debug]Loading env
Run tj-actions/changed-files@v37
::group::changed-files
changed-files
::group::changed-files-patterns
changed-files-patterns
##[debug]Node Action run completed with exit code 0
##[debug]Set output added_files = 
##[debug]Set output added_files_count = 0
##[debug]Set output copied_files = 
##[debug]Set output copied_files_count = 0
##[debug]Set output modified_files = 
##[debug]Set output modified_files_count = 0
##[debug]Set output renamed_files = 
##[debug]Set output renamed_files_count = 0
##[debug]Set output type_changed_files = 
##[debug]Set output type_changed_files_count = 0
##[debug]Set output unmerged_files = 
##[debug]Set output unmerged_files_count = 0
##[debug]Set output unknown_files = 
##[debug]Set output unknown_files_count = 0
##[debug]Set output all_changed_and_modified_files = 
##[debug]Set output all_changed_and_modified_files_count = 0
##[debug]Set output all_changed_files = 
##[debug]Set output all_changed_files_count = 0
##[debug]Set output any_changed = false
##[debug]Set output only_changed = false
##[debug]Set output other_changed_files = supabase/functions/_src/season-data/s01.ts
##[debug]Set output other_changed_files_count = 1
##[debug]Set output all_modified_files = 
##[debug]Set output all_modified_files_count = 0
##[debug]Set output any_modified = false
##[debug]Set output only_modified = false
##[debug]Set output other_modified_files = supabase/functions/_src/season-data/s01.ts
##[debug]Set output other_modified_files_count = 1
##[debug]Set output deleted_files = 
##[debug]Set output deleted_files_count = 0
##[debug]Set output any_deleted = false
##[debug]Set output only_deleted = false
##[debug]Set output other_deleted_files = 
##[debug]Set output other_deleted_files_count = 0
##[debug]Finishing: check for file changes
```

**Comment by jackton1** [comment]
@danielstaleiny It appears you are missing `/` and you'll need to use:

`supabase/functions/_src/**/*.{js,ts,json}` to  match `supabase/functions/_src/season-data/s01.ts`

Notice this `supabase/functions/_src/**.{js,ts,json}` doesn't match `/` between `src` and `season-data`

**Comment by jackton1** [comment]
You can use this site to test your glob patterns

 https://codepen.io/mrmlnc/pen/OXQjMe
